[package]
name = "assembler"
version = "0.1.0"

[dependencies]
clap = "2.32.0"
log = "0.4.6"
env_logger = "0.6.1"
failure = "0.1.5"
gb-io = { git = "https://github.com/dlesl/gb-io" }
assembly = { path = "../.." }
